In [1]:
import json
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import imblearn
import datetime

import warnings
warnings.filterwarnings("ignore")

from matplotlib import style
style.use('dark_background')
pd.set_option('display.max_columns', 150)
pd.set_option('display.max_rows', 150)
style.use('dark_background')

In [2]:
os.getcwd()

'/home/gary/Springboard/relax_challenge'

In [3]:
users = pd.read_csv('takehome_users.csv', encoding='latin1')
users

,object_id,creation_time,name,email,creation_source,last_session_creation_time,opted_in_to_mailing_list,enabled_for_marketing_drip,org_id,invited_by_user_id
0,1,2014-04-22 03:53:30,Clausen August,AugustCClausen@yahoo.com,GUEST_INVITE,1.398139e+09,1,0,11,10803.0
1,2,2013-11-15 03:45:04,Poole Matthew,MatthewPoole@gustr.com,ORG_INVITE,1.396238e+09,0,0,1,316.0
2,3,2013-03-19 23:14:52,Bottrill Mitchell,MitchellBottrill@gustr.com,ORG_INVITE,1.363735e+09,0,0,94,1525.0
3,4,2013-05-21 08:09:28,Clausen Nicklas,NicklasSClausen@yahoo.com,GUEST_INVITE,1.369210e+09,0,0,1,5151.0
4,5,2013-01-17 10:14:20,Raw Grace,GraceRaw@yahoo.com,GUEST_INVITE,1.358850e+09,0,0,193,5240.0
...,...,...,...,...,...,...,...,...,...,...
11995,11996,2013-09-06 06:14:15,Meier Sophia,SophiaMeier@gustr.com,ORG_INVITE,1.378448e+09,0,0,89,8263.0
11996,11997,2013-01-10 18:28:37,Fisher Amelie,AmelieFisher@gmail.com,SIGNUP_GOOGLE_AUTH,1.358275e+09,0,0,200,NaN
11997,11998,2014-04-27 12:45:16,Haynes Jake,JakeHaynes@cuvox.de,GUEST_INVITE,1.398603e+09,1,1,83,8074.0
11998,11999,2012-05-31 11:55:59,Faber Annett,mhaerzxp@iuxiw.com,PERSONAL_PROJECTS,1.338638e+09,0,0,6,NaN
11999,12000,2014-01-26 08:57:12,Lima Thaís,ThaisMeloLima@hotmail.com,SIGNUP,1.390727e+09,0,1,0,NaN

In [4]:
ue = pd.read_csv('takehome_user_engagement.csv', index_col = 'time_stamp', parse_dates=['time_stamp'])
ue = ue.sort_values(['user_id', 'time_stamp'])
ue['adopted'] = 0
for i in ue.user_id:    
    ue['adopted'].loc[ue['user_id'] == i] = ue['visited'].loc[ue.user_id == i].rolling('7D', min_periods = 3).count()
ue = ue.fillna(0)    

ue.head(100)

                     user_id  visited  adopted
time_stamp
2014-04-22 03:53:30        1        1      0.0
2013-11-15 03:45:04        2        1      0.0
2013-11-29 03:45:04        2        1      0.0
2013-12-09 03:45:04        2        1      0.0
2013-12-25 03:45:04        2        1      0.0
2013-12-31 03:45:04        2        1      0.0
2014-01-08 03:45:04        2        1      0.0
2014-02-03 03:45:04        2        1      0.0
2014-02-08 03:45:04        2        1      0.0
2014-02-09 03:45:04        2        1      3.0
2014-02-13 03:45:04        2        1      3.0
2014-02-16 03:45:04        2        1      0.0
2014-03-09 03:45:04        2        1      0.0
2014-03-13 03:45:04        2        1      0.0
2014-03-31 03:45:04        2        1      0.0
2013-03-19 23:14:52        3        1      0.0
2013-05-22 08:09:28        4        1      0.0
2013-01-22 10:14:20        5        1      0.0
2013-12-19 03:37:06        6        1      0.0
2012-12-20 13:24:32        7        1      0.0
2013-01-16 22:08:03       10        1      0.0
2013-01-22 22:08:03       10        1      0.0
2013-01-30 22:08:03       10        1      0.0
2013-02-04 22:08:03       10        1      0.0
2013-02-06 22:08:03       10        1      0.0
2013-02-14 22:08:03       10        1      0.0
2013-02-17 22:08:03       10        1      0.0
2013-02-19 22:08:03       10        1      3.0
2013-02-26 22:08:03       10        1      0.0
2013-03-01 22:08:03       10        1      0.0
2013-03-02 22:08:03       10        1      3.0
2013-03-05 22:08:03       10        1      3.0
2013-03-09 22:08:03       10        1      0.0
2013-03-15 22:08:03       10        1      0.0
2013-03-17 22:08:03       10        1      0.0
2013-03-20 22:08:03       10        1      3.0
2013-03-22 22:08:03       10        1      3.0
2013-03-26 22:08:03       10        1      3.0
2013-04-07 22:08:03       10        1      0.0
2013-04-11 22:08:03       10        1      0.0
2013-04-13 22:08:03       10        1      3.0
2013-04-14 22:08:03       10        1      3.0
2013-04-17 22:08:03       10        1      4.0
2013-04-19 22:08:03       10        1      4.0
2013-04-24 22:08:03       10        1      0.0
2013-04-26 22:08:03       10        1      0.0
2013-04-27 22:08:03       10        1      3.0
2013-04-30 22:08:03       10        1      4.0
2013-05-01 22:08:03       10        1      4.0
2013-05-02 22:08:03       10        1      5.0
2013-05-03 22:08:03       10        1      5.0
2013-05-06 22:08:03       10        1      5.0
2013-05-07 22:08:03       10        1      5.0
2013-05-08 22:08:03       10        1      5.0
2013-05-10 22:08:03       10        1      4.0
2013-05-12 22:08:03       10        1      5.0
2013-05-15 22:08:03       10        1      3.0
2013-05-17 22:08:03       10        1      3.0
2013-05-18 22:08:03       10        1      4.0
2013-05-23 22:08:03       10        1      3.0
2013-05-24 22:08:03       10        1      3.0
2013-05-27 22:08:03       10        1      3.0
2013-05-29 22:08:03       10        1      4.0
2013-06-03 22:08:03       10        1      0.0
2013-06-04 22:08:03       10        1      3.0
2013-06-07 22:08:03       10        1      3.0
2013-06-09 22:08:03       10        1      4.0
2013-06-10 22:08:03       10        1      4.0
2013-06-11 22:08:03       10        1      4.0
2013-06-13 22:08:03       10        1      5.0
2013-06-15 22:08:03       10        1      5.0
2013-06-16 22:08:03       10        1      5.0
2013-06-17 22:08:03       10        1      5.0
2013-06-18 22:08:03       10        1      5.0
2013-06-22 22:08:03       10        1      4.0
2013-06-26 22:08:03       10        1      0.0
2013-06-28 22:08:03       10        1      3.0
2013-06-30 22:08:03       10        1      3.0
2013-07-03 22:08:03       10        1      3.0
2013-07-04 22:08:03       10        1      4.0
2013-07-05 22:08:03       10        1      4.0
2013-07-06 22:08:03       10        1      5.0
2013-07-08 22:08:03       10        1      5.0
2013-07-09 22:08:03       10        1      6.0
2013-07-13 22:08:03       10        1      3.0
2013-07-16 22:08:03       10        1      0.0
2013-07-17 22:08:03       10        1      3.0
2013-07-18 22:08:03       10        1      4.0
2013-07-20 22:08:03       10        1      4.0
2013-07-21 22:08:03       10        1      5.0
2013-07-22 22:08:03       10        1      6.0
2013-07-24 22:08:03       10        1      5.0
2013-07-25 22:08:03       10        1      5.0
2013-07-28 22:08:03       10        1      4.0
2013-07-29 22:08:03       10        1      4.0
2013-07-30 22:08:03       10        1      5.0
2013-08-02 22:08:03       10        1      4.0
2013-08-03 22:08:03       10        1      5.0
2013-08-04 22:08:03       10        1      5.0
2013-08-06 22:08:03       10        1      4.0

In [5]:
ue2 = ue

for i in ue2.user_id:    
    if ue2['adopted'].loc[ue2['user_id'] == i].max() > 0:
        ue2['adopted'].loc[ue2['user_id'] == i] = 1
    else:
        ue2['adopted'].loc[ue2['user_id'] == i] = 0

In [6]:
ue2

                     user_id  visited  adopted
time_stamp
2014-04-22 03:53:30        1        1      0.0
2013-11-15 03:45:04        2        1      1.0
2013-11-29 03:45:04        2        1      1.0
2013-12-09 03:45:04        2        1      1.0
2013-12-25 03:45:04        2        1      1.0
...                      ...      ...      ...
2013-09-06 06:14:15    11996        1      0.0
2013-01-15 18:28:37    11997        1      0.0
2014-04-27 12:45:16    11998        1      0.0
2012-06-02 11:55:59    11999        1      0.0
2014-01-26 08:57:12    12000        1      0.0

[207917 rows x 3 columns]

In [7]:
ue3 = ue2
ue3.columns = ['object_id', 'avg_daily_visits', 'adopted']
ue3 = ue3.groupby(by = ['object_id']).agg(lambda x:x.value_counts().index[0])
users2 = users.drop(['name', 'email', 'last_session_creation_time'], axis = 1)
ue3 = ue3.merge(users2, how = 'outer', on = 'object_id')
for i in ue3['object_id']:
    if ue3['invited_by_user_id'].loc[ue3['object_id'] == i].max() > 0.0:
        ue3['invited_by_user_id'].loc[ue3['object_id'] == i] = 1
    else:
        ue3['invited_by_user_id'].loc[ue3['object_id'] == i] = 0
   
ue3.head(100)

,object_id,avg_daily_visits,adopted,creation_time,creation_source,opted_in_to_mailing_list,enabled_for_marketing_drip,org_id,invited_by_user_id
0,1,1.0,0.0,2014-04-22 03:53:30,GUEST_INVITE,1,0,11,1.0
1,2,1.0,1.0,2013-11-15 03:45:04,ORG_INVITE,0,0,1,1.0
2,3,1.0,0.0,2013-03-19 23:14:52,ORG_INVITE,0,0,94,1.0
3,4,1.0,0.0,2013-05-21 08:09:28,GUEST_INVITE,0,0,1,1.0
4,5,1.0,0.0,2013-01-17 10:14:20,GUEST_INVITE,0,0,193,1.0
5,6,1.0,0.0,2013-12-17 03:37:06,GUEST_INVITE,0,0,197,1.0
6,7,1.0,0.0,2012-12-16 13:24:32,SIGNUP,0,1,37,0.0
7,10,1.0,1.0,2013-01-16 22:08:03,ORG_INVITE,1,1,318,1.0
8,11,1.0,0.0,2013-12-26 03:55:54,SIGNUP,0,0,69,0.0
9,13,1.0,0.0,2014-03-30 16:19:38,ORG_INVITE,0,0,254,1.0
10,14,1.0,0.0,2012-10-11 16:14:33,SIGNUP,0,0,0,0.0
11,17,1.0,0.0,2014-04-09 14:39:38,GUEST_INVITE,1,0,175,1.0
12,19,1.0,0.0,2013-05-24 14:56:36,SIGNUP,1,0,0,0.0
13,20,1.0,1.0,2014-03-06 11:46:38,SIGNUP,0,0,58,0.0
14,21,1.0,0.0,2013-01-22 12:27:42,PERSONAL_PROJECTS,0,0,54,0.0
15,22,1.0,0.0,2014-02-10 06:00:46,ORG_INVITE,0,0,7,1.0
16,23,1.0,0.0,2012-08-17 08:30:27,ORG_INVITE,1,0,6,1.0
17,24,1.0,0.0,2013-09-09 22:20:03,SIGNUP,1,0,123,0.0
18,25,1.0,0.0,2014-02-25 00:11:13,GUEST_INVITE,1,0,81,1.0
19,27,1.0,0.0,2014-01-14 17:35:11,ORG_INVITE,0,0,134,1.0
20,28,1.0,0.0,2013-02-11 20:00:25,SIGNUP,0,0,6,0.0
21,29,1.0,0.0,2013-09-16 02:08:41,SIGNUP,0,0,92,0.0
22,30,1.0,0.0,2013-06-04 00:44:25,GUEST_INVITE,0,0,251,1.0
23,31,1.0,0.0,2014-01-23 05:21:42,SIGNUP,0,0,283,0.0
24,33,1.0,1.0,2014-03-11 06:29:09,GUEST_INVITE,0,0,401,1.0
25,36,1.0,0.0,2013-08-06 09:08:15,GUEST_INVITE,1,0,109,1.0
26,37,1.0,0.0,2012-09-25 14:37:23,SIGNUP,0,0,276,0.0
27,41,1.0,0.0,2014-04-30 23:38:17,ORG_INVITE,0,0,64,1.0
28,42,1.0,1.0,2012-11-11 19:05:07,SIGNUP,1,0,235,0.0
29,43,1.0,1.0,2012-12-31 07:13:17,GUEST_INVITE,0,0,63,1.0
30,44,1.0,0.0,2014-05-28 16:43:12,SIGNUP,0,0,14,0.0
31,45,1.0,0.0,2014-04-29 21:55:19,SIGNUP_GOOGLE_AUTH,1,0,4,0.0
32,46,1.0,0.0,2014-01-01 18:42:08,ORG_INVITE,0,0,127,1.0
33,47,1.0,0.0,2012-06-07 13:23:02,ORG_INVITE,1,1,32,1.0
34,48,1.0,0.0,2013-11-03 14:37:00,ORG_INVITE,0,0,224,1.0
35,49,1.0,0.0,2013-10-13 10:06:52,SIGNUP,0,0,304,0.0
36,50,1.0,1.0,2012-06-03 11:02:08,GUEST_INVITE,0,0,61,1.0
37,51,1.0,0.0,2013-08-22 09:53:43,ORG_INVITE,0,1,0,1.0
38,53,1.0,1.0,2013-02-09 23:47:15,GUEST_INVITE,0,0,37,1.0
39,54,1.0,0.0,2013-03-17 12:31:27,GUEST_INVITE,1,1,51,1.0
40,55,1.0,0.0,2012-07-18 23:00:26,SIGNUP_GOOGLE_AUTH,0,0,229,0.0
41,56,1.0,0.0,2013-12-01 08:50:02,GUEST_INVITE,0,0,229,1.0
42,57,1.0,0.0,2013-11-18 17:48:04,GUEST_INVITE,0,0,88,1.0
43,58,1.0,0.0,2013-01-28 17:44:26,ORG_INVITE,1,0,304,1.0
44,59,1.0,0.0,2014-03-07 03:21:57,SIGNUP_GOOGLE_AUTH,0,0,325,0.0
45,60,1.0,0.0,2014-03-21 22:56:03,ORG_INVITE,0,0,88,1.0
46,61,1.0,0.0,2014-05-14 03:45:47,SIGNUP_GOOGLE_AUTH,0,0,150,0.0
47,63,1.0,1.0,2012-12-20 16:30:52,SIGNUP_GOOGLE_AUTH,0,0,203,0.0
48,64,1.0,0.0,2014-03-13 22:02:50,SIGNUP,0,0,21,0.0
49,65,1.0,0.0,2013-08-27 00:38:29,SIGNUP_GOOGLE_AUTH,0,0,409,0.0
50,66,1.0,0.0,2014-02-03 14:50:52,ORG_INVITE,0,0,215,1.0
51,67,1.0,0.0,2014-04-23 10:52:20,ORG_INVITE,0,0,141,1.0
52,68,1.0,0.0,2014-01-22 08:24:31,SIGNUP_GOOGLE_AUTH,1,0,5,0.0
53,69,1.0,1.0,2012-06-29 10:15:18,GUEST_INVITE,0,0,107,1.0
54,72,1.0,0.0,2013-08-21 11:56:14,SIGNUP,0,0,367,0.0
55,73,1.0,0.0,2013-04-16 17:32:43,ORG_INVITE,0,0,389,1.0
56,74,1.0,1.0,2013-01-14 00:02:41,SIGNUP_GOOGLE_AUTH,0,0,89,0.0
57,75,1.0,0.0,2014-01-25 01:05:21,SIGNUP,0,0,242,0.0
58,76,1.0,0.0,2014-05-17 16:58:45,SIGNUP,1,1,51,0.0
59,77,1.0,0.0,2012-12-20 16:31:21,SIGNUP,1,1,68,0.0
60,78,1.0,0.0,2012-06-28 17:36:39,PERSONAL_PROJECTS,1,0,16,0.0
61,80,1.0,1.0,2014-02-28 21:30:38,ORG_INVITE,1,1,49,1.0
62,81,1.0,1.0,2013-06-26 03:57:41,PERSONAL_PROJECTS,1,0,185,0.0
63,82,1.0,1.0,2013-02-12 02:10:40,GUEST_INVITE,0,0,91,1.0
64,83,1.0,0.0,2013-01-26 09:44:23,ORG_INVITE,1,0,172,1.0
65,84,1.0,0.0,2014-01-28 04:48:29,ORG_INVITE,0,0,8,1.0
66,85,1.0,0.0,2013-08-16 18:00:53,ORG_INVITE,1,1,43,1.0
67,86,1.0,0.0,2012-11-11 02:50:15,ORG_INVITE,0,0,249,1.0
68,87,1.0,1.0,2013-09-11 22:53:29,SIGNUP,1,0,26,0.0
69,88,1.0,0.0,2012-08-16 10:42:26,SIGNUP,0,0,139,0.0
70,89,1.0,0.0,2012-08-07 22:12:00,SIGNUP,0,0,70,0.0
71,90,1.0,0.0,2013-08-07 00:33:23,ORG_INVITE,0,0,10,1.0
72,91,1.0,0.0,2013-03-19 17:20:36,SIGNUP,0,0,252,0.0
73,92,1.0,0.0,2013-02-24 20:33:23,SIGNUP_GOOGLE_AUTH,0,0,91,0.0
74,94,1.0,0.0,2013-06-04 13:58:03,SIGNUP,0,0,69,0.0
75,95,1.0,0.0,2014-03-09 06:30:04,PERSONAL_PROJECTS,0,0,119,0.0
76,96,1.0,0.0,2014-03-12 00:33:22,ORG_INVITE,0,0,130,1.0
77,97,1.0,0.0,2013-10-02 20:29:41,SIGNUP_GOOGLE_AUTH,0,0,3,0.0
78,98,1.0,0.0,2014-05-13 15:52:03,ORG_INVITE,0,0,196,1.0
79,99,1.0,0.0,2012-09-26 23:27:02,ORG_INVITE,0,1,335,1.0
80,100,1.0,0.0,2013-06-14 08:41:36,ORG_INVITE,0,0,375,1.0
81,101,1.0,0.0,2013-08-15 22:38:05,GUEST_INVITE,0,0,303,1.0
82,103,1.0,0.0,2012-12-02 10:44:08,GUEST_INVITE,1,1,25,1.0
83,105,1.0,0.0,2012-11-23 14:35:19,ORG_INVITE,1,1,134,1.0
84,106,1.0,0.0,2012-09-22 06:34:37,PERSONAL_PROJECTS,0,0,83,0.0
85,107,1.0,0.0,2013-09-20 05:39:25,SIGNUP,0,0,27,0.0
86,109,1.0,0.0,2012-08-28 05:18:22,SIGNUP,1,0,118,0.0
87,110,1.0,0.0,2013-11-01 14:02:47,ORG_INVITE,0,0,295,1.0
88,111,1.0,0.0,2013-08-31 02:56:48,SIGNUP,0,0,19,0.0
89,112,1.0,0.0,2012-12-09 08:21:30,ORG_INVITE,0,0,301,1.0
90,113,1.0,0.0,2014-04-24 19:07:55,SIGNUP,0,0,100,0.0
91,114,1.0,0.0,2014-05-30 14:33:37,GUEST_INVITE,0,0,112,1.0
92,115,1.0,0.0,2014-05-27 21:26:58,GUEST_INVITE,0,0,263,1.0
93,116,1.0,0.0,2012-09-04 01:40:16,ORG_INVITE,0,0,0,1.0
94,117,1.0,0.0,2013-08-04 05:52:15,GUEST_INVITE,0,0,39,1.0
95,119,1.0,0.0,2012-09-24 01:04:25,SIGNUP,0,0,184,0.0
96,121,1.0,0.0,2013-01-03 23:57:39,GUEST_INVITE,1,0,402,1.0
97,123,1.0,0.0,2014-03-15 16:49:14,SIGNUP,0,0,103,0.0
98,124,1.0,0.0,2013-05-01 00:23:57,PERSONAL_PROJECTS,0,0,373,0.0
99,125,1.0,0.0,2013-05-26 20:51:51,ORG_INVITE,0,0,268,1.0

In [31]:
df = ue3.dropna().drop(['object_id'], axis = 1)
df['org_id'] = df[['org_id']].astype('category',copy=False)
df['creation_time']= pd.to_datetime(df['creation_time'])

p = df['creation_source']
onehot = pd.get_dummies(p)
df = pd.concat([df, onehot], axis=1)
df = df.dropna().drop(['creation_source', 'org_id', 'creation_time'], axis = 1)
df = df.reset_index(drop=True)

df

,avg_daily_visits,adopted,opted_in_to_mailing_list,enabled_for_marketing_drip,invited_by_user_id,GUEST_INVITE,ORG_INVITE,PERSONAL_PROJECTS,SIGNUP,SIGNUP_GOOGLE_AUTH
0,1.0,0.0,1,0,1.0,1,0,0,0,0
1,1.0,1.0,0,0,1.0,0,1,0,0,0
2,1.0,0.0,0,0,1.0,0,1,0,0,0
3,1.0,0.0,0,0,1.0,1,0,0,0,0
4,1.0,0.0,0,0,1.0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8818,1.0,0.0,0,0,1.0,0,1,0,0,0
8819,1.0,0.0,0,0,0.0,0,0,0,0,1
8820,1.0,0.0,1,1,1.0,1,0,0,0,0
8821,1.0,0.0,0,0,0.0,0,0,1,0,0
8822,1.0,0.0,0,1,0.0,0,0,0,1,0

In [40]:
from imblearn.over_sampling import SMOTE

X = df.drop(['adopted'], axis = 1)
y = df['adopted']

sm = SMOTE(random_state=42)
X, y = sm.fit_resample(X, y)

In [41]:
from sklearn.model_selection import train_test_split

xtr, xte, ytr, yte = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

pg = {'C':[0.001, 0.01, 0.1, 1, 10, 100, 1000]}
clf = LogisticRegression()
clf_cv= GridSearchCV(estimator = clf, param_grid = pg, cv = 5)
clf_cv.fit(X, y)

print("Best Score:" + str(clf_cv.best_score_))
print("Best Parameters: " + str(clf_cv.best_params_))

Best Score:0.5361448622101792
Best Parameters: {'C': 0.001}

In [43]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

clf = LogisticRegression(C = clf_cv.best_params_['C'])
clf.fit(xte, yte)
ypr = clf.predict(xte)
print(confusion_matrix(yte, ypr), classification_report(yte, ypr))

[[674 768]
 [604 843]]               precision    recall  f1-score   support

         0.0       0.53      0.47      0.50      1442
         1.0       0.52      0.58      0.55      1447

    accuracy                           0.53      2889
   macro avg       0.53      0.52      0.52      2889
weighted avg       0.53      0.53      0.52      2889

In [44]:
from sklearn.neighbors import KNeighborsClassifier

pg = {'n_neighbors':np.arange(1, 30)}
knn = KNeighborsClassifier()
knn_cv= GridSearchCV(estimator = knn, param_grid = pg, cv = 5)
knn_cv.fit(X, y)

print("Best Score:" + str(knn_cv.best_score_))
print("Best Parameters: " + str(knn_cv.best_params_))

Best Score:0.510456272670527
Best Parameters: {'n_neighbors': 29}

In [45]:
knn = KNeighborsClassifier(knn_cv.best_params_['n_neighbors'])
knn.fit(xte, yte)
ypr = knn.predict(xte)
print(confusion_matrix(yte, ypr), classification_report(yte, ypr))

[[776 666]
 [682 765]]               precision    recall  f1-score   support

         0.0       0.53      0.54      0.54      1442
         1.0       0.53      0.53      0.53      1447

    accuracy                           0.53      2889
   macro avg       0.53      0.53      0.53      2889
weighted avg       0.53      0.53      0.53      2889

In [46]:
from sklearn.ensemble import RandomForestClassifier

pg = {'bootstrap':[True, False], 
      'max_depth':np.arange(2, 10), 
      'min_samples_leaf': np.arange(2, 5), 
      'min_samples_split': np.arange(2, 5)}
forest = RandomForestClassifier(n_estimators = 100)
forest_cv= GridSearchCV(estimator = forest, param_grid = pg, cv = 5)
forest_cv.fit(X, y)

print("Best Score:" + str(forest_cv.best_score_))
print("Best Parameters: " + str(forest_cv.best_params_))

Best Score:0.5408529247916205
Best Parameters: {'bootstrap': True, 'max_depth': 5, 'min_samples_leaf': 2, 'min_samples_split': 2}

In [47]:
forest = RandomForestClassifier(n_estimators = 1000, 
                                bootstrap = forest_cv.best_params_['bootstrap'], 
                                max_depth = forest_cv.best_params_['max_depth'], 
                                min_samples_leaf = forest_cv.best_params_['min_samples_leaf'], 
                                min_samples_split = forest_cv.best_params_['min_samples_split'])
forest.fit(xte, yte)
ypr = forest.predict(xte)
print(confusion_matrix(y_true = yte, y_pred = ypr), classification_report(yte, ypr))

[[1022  420]
 [ 901  546]]               precision    recall  f1-score   support

         0.0       0.53      0.71      0.61      1442
         1.0       0.57      0.38      0.45      1447

    accuracy                           0.54      2889
   macro avg       0.55      0.54      0.53      2889
weighted avg       0.55      0.54      0.53      2889